export const FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE';
export const UPDATE_EMPLOYEE_INFO = 'UPDATE_EMPLOYEE_INFO';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';

